config/routes.rb
Rails.application.routes.draw do
  resources :exchange_operations, only: [:index, :show, :new, :create]
  resources :exchange_rates, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange_operation.rb
class ExchangeOperation < ApplicationRecord

  validates_presence_of :from_currency, :amount, :to_currency

  before_save :set_result

  def set_result
    rate = ExchangeRate.where(source_currency: self.from_currency, target_currency: self.to_currency).first.try(:rate)
    self.result = self.amount * rate
  end

end

app/models/exchange_rate.rb
class ExchangeRate < ApplicationRecord

  validates_presence_of :source_currency, :target_currency, :rate

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchange_operations_controller.rb
class ExchangeOperationsController < ApplicationController
  before_action :set_exchange_operation, only: [:show]

  def index
    @exchange_operations = ExchangeOperation.all
  end

  def show
  end

  def new
    @exchange_operation = ExchangeOperation.new
  end

  def create
    @exchange_operation = ExchangeOperation.new(exchange_operation_params)

    if @exchange_operation.save
      redirect_to @exchange_operation, notice: 'Exchange operation was successfully created.'
    else
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange_operation
      @exchange_operation = ExchangeOperation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exchange_operation_params
      params.require(:exchange_operation).permit(:from_currency, :amount, :to_currency, :result)
    end
end

app/controllers/exchange_rates_controller.rb
class ExchangeRatesController < ApplicationController

  def new
    @exchange_rate = ExchangeRate.new
  end

  def create
    @service = Services::ExchangeRates::Retrive.new
    @service.perform
    redirect_to exchange_operations_path, notice: 'Exchange rates was successfully created.'
  rescue => e
    redirect_to action: :new, notice: e.message
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchange_operations/_form.html.erb
<%= form_with(model: exchange_operation, local: true) do |form| %>
  <% if exchange_operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange_operation.errors.count, "error") %> prohibited this exchange_operation from being saved:</h2>

      <ul>
      <% exchange_operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   Type: EUR
    <%= form.label :from_currency %>
    <%= form.text_field :from_currency %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  Type: USD or CHF
  <div class="field">
    <%= form.label :to_currency %>
    <%= form.text_field :to_currency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exchange_operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exchange Operations</h1>

<table>
  <thead>
    <tr>
      <th>From currency</th>
      <th>Amount</th>
      <th>To currency</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchange_operations.each do |exchange_operation| %>
      <tr>
        <td><%= exchange_operation.from_currency %></td>
        <td><%= exchange_operation.amount %></td>
        <td><%= exchange_operation.to_currency %></td>
        <td><%= exchange_operation.result %></td>
        <td><%= link_to 'Show', exchange_operation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange Operation', new_exchange_operation_path %>

app/views/exchange_operations/new.html.erb
<h1>New Exchange Operation</h1>

<%= render 'form', exchange_operation: @exchange_operation %>

<%= link_to 'Back', exchange_operations_path %>

app/views/exchange_operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From currency:</strong>
  <%= @exchange_operation.from_currency %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @exchange_operation.amount %>
</p>

<p>
  <strong>To currency:</strong>
  <%= @exchange_operation.to_currency %>
</p>

<p>
  <strong>Result:</strong>
  <%= @exchange_operation.result %>
</p>

<%= link_to 'Back', exchange_operations_path %>

app/views/exchange_rates/_form.html.erb
<%= form_with(model: exchange_rate, local: true) do |form| %>
  <% if exchange_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange_rate.errors.count, "error") %> prohibited this exchange_rate from being saved:</h2>

      <ul>
      <% exchange_rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--  <div class="field">-->
    <%#= form.label :source_currency %>
    <%#= form.text_field :source_currency %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :target_currency %>
    <%#= form.text_field :target_currency %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :rate %>
    <%#= form.text_field :rate %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit "Get current currency rate" %>
  </div>
<% end %>

app/views/exchange_rates/new.html.erb
<h1>New Exchange Rate</h1>

<%= render 'form', exchange_rate: @exchange_rate %>

<%= link_to 'Back', exchange_rates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyDataChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>